### ISSUE TITLE
Suggestions on splitting up files

### ISSUE THREAD

**Issue by Ronsku** [Dynalon/reactive-state#1]
Hi, Thanks again for sharing this amazing library. I really like the concept and how it works.

I'm trying it out right now to build it into a smart file architecture. My thoughts so far is that I would have following simple file setup:
```
- store.ts
- reducers/counter.ts
- reducers/name.ts
- reducers/...
```
In reducers I would create their own interface and initial states and import them to the store.ts like `this:`

```
import { Store, Reducer, Action } from 'reactive-state';
import { CounterState, counterInitialState } from './reducers/counter';

interface AppState {
	counter: CounterState;
}

const appInitialState = {
	counter: counterInitialState
}
```
Everything so far looks good. Where I come to issues are when I create Action subjects and Reducer functions in the reducer files and want to `addReducer` them on the root store.
I cannot cross reference the store.ts and counter.ts like this obviously:

```
import { store, AppState } from './../store';

export interface CounterState {
	value?: number;
}

export const counterInitialState: CounterState = {
	value: 0
};

const incrementAction = new Action<number>();
const incrementReducer: Reducer<AppState, number> = (state, payload) => {
	return { ...state, counter: state.counter.value + payload };
};

store.addReducer(incrementAction, incrementReducer);
```
since the store wont have been created yet when trying to access it in the reducer. I guess this could be solved in some ugly asynchronous way, but I would not like that.
(here I'm also thinking about using `Reducer<CounterState...>` instead of `Reducer<AppState...>`)

One way to solve it would be to import every action and reducer in store.ts from counter.ts, but that would be a very big import list.
`import { CounterState, counterInitialState, incrementAction,  incrementReducer ... } from './reducers/counter';`

In your old version of `reactive-state` you've built the addReducer function by taking a spread parameter where you could add all your reducers at once, could something like this be created? Then I could just create an array of actions/reducers and import that and pass it into the addReducer function. I know I can also create some custom loop that goes through it, but it doesn't feel clean either.

How would you suggest splitting store and reducers apart from each other. After I get this done I'm going to start thinking about the selectors and how to use the slices in an optimal way.

Thank you again!

**Comment by Dynalon** [comment]
First of all, cross-referencing is something perfectly valid in ES6 and TypeScript (circular module dependencies are explicitly allowed), but I agree, it is a bad practice to have them. An exception are *Types* (`interface` and `type` keyword in TypeScript) - you can always cross-reference them and at some point this will happen in your typescript project. If you import a *type* in TypeScript, this import will not make it into the compiled JS output - it does thus not affect your runtime dependencies at all. But again, clean architecture should avoid that.

While it would be possible that your counter module could reference global AppState, I too think it is bad practice - because counter is an independent module that should know nothing about the AppState type. Thats where the [store slicing](https://github.com/Dynalon/reactive-state/wiki/Slicing-the-State) comes into play, used in conjunction with Inversion of Control (aka the Hollywood Principle: "Don't call us, we call YOU!").

Given that, I suggest the following layout (lets assume that counter is a separate module and gets its own folder, own property on the global AppState etc.)

```
- store.ts
- counter/state.ts (I put actions and reducers in there in this example, you can put them in separate files)

```

Your `store.ts`:
```typescript
import { Store, Reducer, Action } from 'reactive-state';

// the "root" may reference sub-modules (like counter) but not vice-versa
import { CounterState, counterInitialState } from './counter/state';

// import a function that will wire up the reducers and actions
import { registerReducers, counterAction } from './counter/state';

export interface AppState {
	counter: CounterState;
}

const appInitialState = {
    counter: counterInitialState
}

export const appStore = Store.create(appInitialState);
const counterStore: Store<CounterState> = appStore.createSlice("counter");

// ask the counter module to register/wire up the reducers and actions
registerReducers(counterStore);

// dispatch actions at this point
counterAction.next(1);
```

In your `counter/state.ts`:

```typescript
import { Store, Reducer, Action } from "reactive-state";

export interface CounterState {
    counter: number;
}
export const initialCounterState = {
    counter: 0
}

// feel free to put actions and reducer inside the counter/ folder and reference them in this file

export counterAction = new Action<number>();

counterReducer: Reducer<CounterState, number> = (state, payload) => {
    return { ...state, counter: state.counter + payload };
}

export const registerReducers = (store: Store<CounterState>): void => {
    store.addReducer(counterAction, counterReducer);
    store.addReducer(/* ... */);
}
```

This way, everything in the `counter/` folder does not know anything about the AppState, global app store etc. Its just operating on a sub-slice specific to counter. This pretty much follows the approach of using nested `createReducers` in redux.

Note on slicing: Your `appStore` and `counterStore` are linked, meaning they hold the same state. If you change something in one store (by dispatching an action), both stores will update the state correctly. Do not think of them as different stores, they have just different "views" to the exact same state.

Now, in a real world app you somehow would need to pass the instance of `counterStore` created in the store.ts (which is our app root) back to the counter module at runtime - think a React component `CounterView`. In this case you could pass the `counterStore` through the props of the `CounterView` component. If you mind passing it through the props, your counter module can export a `initialize(store: Store<CounterState>)` function that the root calls upon app initialization (just like registerReducers).

**Comment by Dynalon** [comment]
One thing to mention: If you do not want to use store slicing, there is hardly a way around without cross-referencing: As your reducers need to know the structure of the root state, you must cross-reference `AppState` in your counter, creating a hard dependency on the module. That is highly discouraged, but since you can have type cross-references would be possible.

This only works in plain JavaScript, which would not need to know the structure as it does not have static type system; in typed languages such as Java, C# using the IoC approach I discussed is a common pattern to break up these circular dependencies.

**Comment by Dynalon** [comment]
Update: I edited my answer to include the require type argument when slicing:

```typescript
const counterStore = appStore.createSlice<CounterState>("counter")
```

**Comment by Ronsku** [comment]
@Dynalon you understood my question perfectly. This is exactly what I wanted to do. It all makes sense now when I see the code, but the "slices" made it for some reason confusing when trying to figure it out on my own.. :) What you've build here is exactly what we reactive programming and redux lovers always have been needing!

Now I just need to figure out the smartest and cleanest way of creating selectors. Should be pretty easy with all the already made select functions and slices. Then add redux as a dev-dependency and sync the reactive-state with the redux state to get use of the redux-dev-tools working while developing.

**Comment by Dynalon** [comment]
@Ronsku that is a good idea I haven't thought about; You could on the root store just do a `store.select(s => s).subscribe(state => syncStateToRedux(state))` where `syncStateToRedux` just copies the whole state into redux (maybe via a global reducer). Let me know if you get that to work!
