### ISSUE TITLE
Store initialState changed on action dispatch

### ISSUE THREAD

**Issue by Ronsku** [Dynalon/reactive-state#3]
I noticed that the initial state is changed when running following code:

```typescript
interface CounterState {
	value: number;
}

interface AppState {
	counter: CounterState;
}

const counterInitialState: CounterState = {
	value: 0
}

const appInitialState = {
	counter: counterInitialState
}

export const rootState = Store.create(appInitialState);

export const counterAction = new Action<number>();
const counterReducer: Reducer<CounterState, number> = (state, payload = 1) => {
	return { ...state, value: state.value + payload };
}

const counterStore: Store<CounterState> = rootState.createSlice("counter");
counterStore.addReducer(counterAction, counterReducer);

counterAction.next();
counterAction.next();
counterAction.next();

rootState.select(s => s).subscribe(state => {
	console.log(`initial: ${appInitialState.counter.value}`);
	console.log(`state: ${state.counter.value}`);
});
```

Result:
```
initial: 3
state: 3
```

**Comment by Ronsku** [comment]
Followup:

I noticed strange behavior when I tried to update redux store  for redux-dev-tools for development purposes.

Code:
```typescript
interface CounterState {
	value: number;
}

interface AppState {
	counter: CounterState;
}

const counterInitialState: CounterState = {
	value: 0
}

const appInitialState = {
	counter: counterInitialState
}

export const rootState = Store.create(appInitialState);

export const counterAction = new Action<number>();
const counterReducer: Reducer<CounterState, number> = (state, payload = 1) => {
	return { ...state, value: state.value + payload };
}

const counterStore: Store<CounterState> = rootState.createSlice("counter");
counterStore.addReducer(counterAction, counterReducer);

const reducer = (state, action) => {
	return state;
}


const reduxStore = createStore(
	reducer,
	appInitialState,
	window['devToolsExtension'] ? window['devToolsExtension']() : f => f
)

rootState.select(s => s).subscribe(state => {
	console.log(`state: ${state.counter.value}`);
	reduxStore.dispatch({ type: 'ACTION' })
});

counterAction.next();
counterAction.next();
counterAction.next();

```
Creates following output in the redux-dev-tools:
![redux-dev-tools](https://cloud.githubusercontent.com/assets/7983358/26524035/9c62a9a6-432f-11e7-9096-9976ffb96ff5.jpg)

If I update the redux createStore function to:
```

const reduxStore = createStore(
	reducer,
	{ counter: { value: 0 } },
	window['devToolsExtension'] ? window['devToolsExtension']() : f => f
)
```

It will just output the initial state as it should,  (since I don't update the store here just for example purposes).
![redux-dev-tools](https://cloud.githubusercontent.com/assets/7983358/26524048/f162c652-432f-11e7-91bf-a5200c4ea0e8.jpg)

**Comment by Dynalon** [comment]
I can reproduce that, the `appInitialState` object is changed by the inner workings of the store. I.e. your reducer updates the property `counter` and the result is written back to `appInitialState`.

This is a problem (IMHO the initialState should be left untouched) but I don't see how to fix that. All reducers use the initialState object as a basis. While your reducer creates an immutable copy of the `counterInitialState`, updates the `value`to a new number and returns the immutable copy, this copy is written back to the original `appInitialState` object at the `counter` property. This is an update by reference, and thus the change reflects back to the original `appInitialState`.

Now, the issue here is that while I could create an immutable copy inside of `Store.create()` function when you pass an initial state, the problem would still remain if you pass an initial state with lots of deeply nested properties. The only solution would be to deep-clone the full initial state object passed in, but I want to avoid that since: (a) deep cloning done right is difficult (b) people might (even though they shouldn't as its bad practice) have custom objects/classes on the initialState which can not be cloned (think objects that require constructor arguments for creation). So I think deep cloning is not an option here.

I see the following options here:

  1. Tell users and create documentation that the initialState object passed in is subject to change, and if you want an unmodified copy for later use, you have to deep-clone it yourself (for __plain objects__, this can easily be done with `const stateCopy = JSON.parse(JSON.stringify(initialState))`.
  1. Implement deep cloning in the `Store.create()` and `.createSlice()` functions. Drawbacks: We __have__ to throw errors when a user passes in a non-plain object (i.e. an object whose prototype is not `Object`, custom `class`etc.). There is no way of deep-cloning non-plain object graphs.
 
I need more research this more and see how other libraries handle this as they should have the same problems. Maybe there are more options.

For you example, you could fix the problem as suggested in solution (1) be deep cloning the `appInitialState` using  `JSON.parse(JSON.stringify(appInitialState))` and pass in the deep copy to either Redux or `Store.create()`.

**Comment by Dynalon** [comment]
Ok, after looking into Redux I have changed my mind about deep cloning. While Redux does not need to deep clone (because the composeReducers will call the reducer with an undefined state in which case the composed reducer **must** return an initial state for that slice), it does perform plain object checks using lodash's `isPlainObject` for initialState. I have thus just added same checks for the state in 52675b48a63a and release version 0.0.6 which includes this change and should fix the issue.

We now check every initialState (and cleanupState for `.createSlice()` to be plain objects, and if not, throw an error. It is thus safe to assume we can deepclone it (I re-use `cloneDeep` from lodash for that).
