### ISSUE TITLE
A bit more clear example for connecting with react

### ISSUE THREAD

**Issue by sample-usr** [Dynalon/reactive-state#9]
Hi,
Awesome library! been looking for something like this for a while now. I went through the docs and the example repo but couldn't really find a good way to handle the react connect part. The store/redux part is actually pretty straightforward and quite well written. 
However, when looking at how to connect to react the example repo is probably doing too much in one component that isn't clear enough (e.g. the whole getting the ```connectedComponent``` inside the render function didn't seem clean). 

Could you perhaps provide an example with the HoC pattern, where we can generalize the ```mapToStateProps``` method somehow?

Thanks

**Comment by Dynalon** [comment]
Thanks for the feedback! I have to admit the bridge to React is still highly experimental and kind of my playground. Once the API becomes stable, I should move it into its own `reactive-state-react` (or something with a better name) repo. The non-react part of this project are IMHO pretty mature and well tested (unit tests as well as usage in my own side projects).

As for your questions:

### Q: the whole getting the connectedComponent inside the render function didn't seem clean

A: I totally agree. I find it ugly, but so far nothing better has come to my mind. `react-redux` connects a component *outside*  of the class definition. This is not possible with `reactive-state`, since the reducer composition happens at runtime (in `react-redux` it happens at load time). Thats why the `connect()` method has to be executed after the Component is instanciated. Maybe I can solve this by providing a factory function or something, so we can connect outside of the component: `export default const factory = (store) => connect(Component, store)`. Will have to look into it (suggestions also welcome).


### Q: `mapStateToProps` (I assume is what you meant, since this is used by `react-redux`)

A: In `react-redux`, the `mapStateToProps` function take the State object contained inside of a redux store and "connects" the state object properties to the "props" of the React.Component. It is litteraly "mapping a state object to a props object" as the name suggests :)

Within `reactive-state`, the idea is the same BUT `reactive-state` allow you to use the concept of slices. Since your store maybe a (sub-) slice, the state can have whatever shape - it can even be a single number (not an `Object` as it is the case with redux). Just as the [advanced counter example](https://github.com/Dynalon/reactive-state-react-example/blob/master/src/counter/advanced-counter.tsx#L18) that you noted.

Now, to account for this, the `mapStateToProps` function inside `reactive-state` takes a state, and must return any object (of type Object). This returned object is then feed as input "props" to the component.

Here are some notes/tipps you should think of for the `mapStateToProps` function:

1. Just like a reducer, the `mapStatetoProps` function *should* be a pure function (i.e. has no sideeffects). It simply takes a state as input, and somehow maps it into a new object. Thats why you can put this function outside of the class definition at module scope.
1. If you are using slices and your slice's state matches the props of the component 1:1, you would use the *identity function*: `connect(MyComponent, store, state => state, actionMap)`
1. Try using the identity function when connecting, and print out the props that are passed in the constructor to the component using `console.log`. This might help you to understand how the state is "mapped" to the props.
1. Try using this function: `const mapStateToProps = (state) =>  ({ connectedState: state });`. If you use this function in `connect()`, you just need a single property `connectedState` on your Component's `prop` object. Try to debug/console.log this approach.

Feel free to ask again or make further suggestions. The react bridging is definetely under-documented :(

**Comment by sample-usr** [comment]
@Dynalon Thank you for such a detailed answer!
Yes, I think connecting with react needs to have a new approach. The react-redux way is nice but like you said we can't do it like that in this case. 

I'll keep on experimenting with some ideas I have (maybe hide linking inside the component via decorators for now). And thank you for the insight regarding the ```mapStateToProps```, I'll keep this issue update with my findings (or new questions ;) ).

**Comment by Dynalon** [comment]
I had an idea which I think is a good fit: The `connect()` method just gets the component to connect as argument, and returns a component which is actually a wrapper (hoc) around the original component PLUS it accept the arguments `store`, `mapStateToProps`, `actionMap` as props - this accounts for the fact that those argument are usually available at runtime only (except for mapStateToProps).

I setup a `development` branch in reactive-state and an alpha channel for reactive-state where this is already implemented. To install use `npm install reactive-state@alpha`. The demo app also has a development branch now that uses this alpha.

See [how connect can now be done outside of a class](https://github.com/Dynalon/reactive-state-react-example/blob/development/src/counter/simple-counter.tsx#L30) and [required arguments can easily be bound later on by passing them as props](https://github.com/Dynalon/reactive-state-react-example/blob/development/src/counter/simple-counter.tsx#L69) to the connected component. 

The old method still works, since you can pass all those arguments in an `options` object to `connect()` as second argument.

**Comment by Dynalon** [comment]
I'm closing this as I think with the recent additions to the demo app, there are some more example and an easier API to perform a `connect()` to a component.
